spring:
  h2:
    console:
      enabled: true
      path: /h2-console
  datasource:
    url: jdbc:h2:mem:parkingdb
    driverClassName: org.h2.Driver
    username: sa
    password: password
  jpa:
    database-platform: org.hibernate.dialect.H2Dialect
    hibernate:
      ddl-auto: update
  security:
    oauth2:
      client:
        registration:
          google:
            client-id: 824084755277-c38g7et4ugkomautqnu223q0isl3bk0g.apps.googleusercontent.com
            client-secret: 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
            scope:
              - email
              - profile
server:
  port: 8080
  servlet:
    context-path: /api

frontend:
  url: http://localhost:3000
  dashboard: http://localhost:3000/dashboard
